[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  # Set your contract address here (or configure in Netlify UI under Site settings → Build & deploy → Environment)
  REACT_APP_CONTRACT_ADDRESS = "0xYourContractAddressHere"
